export { helpCommands } from './help/help';
export { iamCommands } from './iam/iam';
export { generateJoke } from './joke/joke';
export { runesCommands } from './runes/runes';
export { setGuest } from './setGuest/setGuest';
export { setGuildie } from './setGuildie/setGuildie';
export { whenIsCommands } from './whenIs/whenIs';
export { etCommand } from './et/et';
export { hi } from './hi/hi';
